/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author shabe
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminControlPanel
     */
    public AdminControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AdminSignOut = new javax.swing.JButton();
        DeleteRecipeButton = new javax.swing.JButton();
        CreateNewRecipeButton = new javax.swing.JButton();
        AdminMenu = new javax.swing.JLabel();
        background5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));
        jPanel1.setFocusable(false);
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        AdminSignOut.setBackground(new java.awt.Color(204, 204, 255));
        AdminSignOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        AdminSignOut.setText("Sign Out");
        AdminSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminSignOutActionPerformed(evt);
            }
        });
        jPanel1.add(AdminSignOut);
        AdminSignOut.setBounds(293, 344, 220, 120);

        DeleteRecipeButton.setBackground(new java.awt.Color(255, 51, 51));
        DeleteRecipeButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        DeleteRecipeButton.setText("Delete Existing Recipe");
        DeleteRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecipeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteRecipeButton);
        DeleteRecipeButton.setBounds(448, 149, 300, 160);

        CreateNewRecipeButton.setBackground(new java.awt.Color(153, 255, 153));
        CreateNewRecipeButton.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        CreateNewRecipeButton.setText("Create New Recipe");
        CreateNewRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewRecipeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateNewRecipeButton);
        CreateNewRecipeButton.setBounds(51, 149, 300, 160);

        AdminMenu.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        AdminMenu.setText("Admin Menu");
        jPanel1.add(AdminMenu);
        AdminMenu.setBounds(287, 35, 270, 90);

        background5.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\background5.png"));
        jPanel1.add(background5);
        background5.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateNewRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewRecipeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewRecipeButtonActionPerformed

    private void AdminSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminSignOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminSignOutActionPerformed

    private void DeleteRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecipeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRecipeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminMenu;
    private javax.swing.JButton AdminSignOut;
    private javax.swing.JButton CreateNewRecipeButton;
    private javax.swing.JButton DeleteRecipeButton;
    private javax.swing.JLabel background5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
