/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author shabe
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminControlPanel
     */
    public AdminControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminMenu = new javax.swing.JLabel();
        CreateNewRecipe = new javax.swing.JButton();
        DeleteRecipe = new javax.swing.JButton();
        BackToLogin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminMenu.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        AdminMenu.setText("Admin Menu");
        getContentPane().add(AdminMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 6, 270, 90));

        CreateNewRecipe.setBackground(new java.awt.Color(153, 255, 153));
        CreateNewRecipe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CreateNewRecipe.setText("Create New Recipe");
        CreateNewRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(CreateNewRecipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 120, 300, 160));

        DeleteRecipe.setBackground(new java.awt.Color(255, 51, 51));
        DeleteRecipe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DeleteRecipe.setText("Delete Existing Recipe");
        DeleteRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecipeActionPerformed(evt);
            }
        });
        getContentPane().add(DeleteRecipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 120, 300, 160));

        BackToLogin.setBackground(new java.awt.Color(204, 204, 255));
        BackToLogin.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        BackToLogin.setText("Back to Login");
        BackToLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginActionPerformed(evt);
            }
        });
        getContentPane().add(BackToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 315, 220, 120));

        jPanel1.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateNewRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateNewRecipeActionPerformed

    private void BackToLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackToLoginActionPerformed

    private void DeleteRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteRecipeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminMenu;
    private javax.swing.JButton BackToLogin;
    private javax.swing.JButton CreateNewRecipe;
    private javax.swing.JButton DeleteRecipe;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
