/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author ethan
 */
public class AllRecipes extends javax.swing.JFrame {

    /**
     * Creates new form AllRecipes
     */
    public AllRecipes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        allRecipesLabel = new javax.swing.JLabel();
        AllRecipesReturnButton = new javax.swing.JButton();
        BreakfastButton = new javax.swing.JButton();
        DinnerButton = new javax.swing.JButton();
        LunchButton = new javax.swing.JButton();
        background4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setForeground(new java.awt.Color(204, 204, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        allRecipesLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        allRecipesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        allRecipesLabel.setText("All Recipes");
        jPanel1.add(allRecipesLabel);
        allRecipesLabel.setBounds(310, 10, 180, 60);

        AllRecipesReturnButton.setBackground(new java.awt.Color(153, 51, 0));
        AllRecipesReturnButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AllRecipesReturnButton.setText("Return");
        AllRecipesReturnButton.setName("AllRecipesReturnButton"); // NOI18N
        AllRecipesReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AllRecipesReturnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(AllRecipesReturnButton);
        AllRecipesReturnButton.setBounds(40, 400, 110, 40);

        BreakfastButton.setBackground(new java.awt.Color(255, 153, 102));
        BreakfastButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BreakfastButton.setText("Breakfast");
        jPanel1.add(BreakfastButton);
        BreakfastButton.setBounds(150, 110, 200, 110);

        DinnerButton.setBackground(new java.awt.Color(204, 153, 0));
        DinnerButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DinnerButton.setText("Dinner");
        jPanel1.add(DinnerButton);
        DinnerButton.setBounds(300, 260, 200, 110);

        LunchButton.setBackground(new java.awt.Color(255, 153, 51));
        LunchButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LunchButton.setText("Lunch");
        jPanel1.add(LunchButton);
        LunchButton.setBounds(440, 110, 200, 110);

        background4.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background4.png"));
        jPanel1.add(background4);
        background4.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AllRecipesReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AllRecipesReturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AllRecipesReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllRecipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllRecipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllRecipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllRecipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllRecipes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AllRecipesReturnButton;
    private javax.swing.JButton BreakfastButton;
    private javax.swing.JButton DinnerButton;
    private javax.swing.JButton LunchButton;
    private javax.swing.JLabel allRecipesLabel;
    private javax.swing.JLabel background4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
