/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author harsi
 */
public class BookmarkView extends javax.swing.JFrame {

    /**
     * Creates new form BookmarkView
     */
    public BookmarkView() {
        initComponents();
    }
    
    public void view(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ingredientspane = new javax.swing.JScrollPane();
        recipe_ingredients = new javax.swing.JTextArea();
        howtopane = new javax.swing.JScrollPane();
        howtopane.setViewportView(recipe_howto);
        howtopane.getVerticalScrollBar().setValue(0);
        recipe_howto = new javax.swing.JTextArea();
        descriptionpane = new javax.swing.JScrollPane();
        recipe_description = new javax.swing.JTextArea();
        cooktimepane = new javax.swing.JScrollPane();
        recipe_cooktime = new javax.swing.JTextArea();
        recipe_name = new javax.swing.JLabel();
        recipe_image = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 800));
        jPanel2.setLayout(null);

        ingredientspane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ingredientspane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ingredientspane.setFocusable(false);

        recipe_ingredients.setEditable(false);
        recipe_ingredients.setBackground(new java.awt.Color(204, 204, 204));
        recipe_ingredients.setColumns(20);
        recipe_ingredients.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        recipe_ingredients.setLineWrap(true);
        recipe_ingredients.setRows(5);
        recipe_ingredients.setWrapStyleWord(true);
        recipe_ingredients.setMaximumSize(new java.awt.Dimension(270, 450));
        recipe_ingredients.setMinimumSize(new java.awt.Dimension(270, 450));
        ingredientspane.setViewportView(recipe_ingredients);

        jPanel2.add(ingredientspane);
        ingredientspane.setBounds(720, 330, 270, 450);

        howtopane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        howtopane.setColumnHeaderView(null);
        howtopane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        howtopane.setFocusCycleRoot(true);
        howtopane.setFocusable(false);
        howtopane.setHorizontalScrollBar(null);
        howtopane.setRowHeaderView(null);
        howtopane.setViewportView(null);

        recipe_howto.setEditable(false);
        recipe_howto.setBackground(new java.awt.Color(204, 204, 204));
        recipe_howto.setColumns(20);
        recipe_howto.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        recipe_howto.setLineWrap(true);
        recipe_howto.setRows(5);
        recipe_howto.setWrapStyleWord(true);
        recipe_howto.setFocusable(false);
        recipe_howto.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                recipe_howtoPropertyChange(evt);
            }
        });
        howtopane.setViewportView(recipe_howto);

        jPanel2.add(howtopane);
        howtopane.setBounds(20, 330, 680, 450);

        descriptionpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        descriptionpane.setFocusable(false);

        recipe_description.setEditable(false);
        recipe_description.setBackground(new java.awt.Color(204, 204, 204));
        recipe_description.setColumns(20);
        recipe_description.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        recipe_description.setLineWrap(true);
        recipe_description.setRows(5);
        recipe_description.setWrapStyleWord(true);
        descriptionpane.setViewportView(recipe_description);

        jPanel2.add(descriptionpane);
        descriptionpane.setBounds(320, 150, 380, 140);

        cooktimepane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        cooktimepane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cooktimepane.setFocusable(false);

        recipe_cooktime.setEditable(false);
        recipe_cooktime.setBackground(new java.awt.Color(204, 204, 204));
        recipe_cooktime.setColumns(20);
        recipe_cooktime.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        recipe_cooktime.setLineWrap(true);
        recipe_cooktime.setRows(5);
        recipe_cooktime.setWrapStyleWord(true);
        cooktimepane.setViewportView(recipe_cooktime);

        jPanel2.add(cooktimepane);
        cooktimepane.setBounds(720, 150, 270, 140);

        recipe_name.setBackground(new java.awt.Color(153, 255, 153));
        recipe_name.setFont(new java.awt.Font("Helvetica Neue", 1, 48)); // NOI18N
        recipe_name.setForeground(new java.awt.Color(102, 255, 153));
        recipe_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(recipe_name);
        recipe_name.setBounds(0, 0, 1000, 80);
        jPanel2.add(recipe_image);
        recipe_image.setBounds(20, 150, 280, 140);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("COOK TIME");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(740, 120, 230, 30);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DESCRIPTION");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(400, 120, 230, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("INGREDIENTS");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(750, 300, 230, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INSTRUCTIONS");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(250, 300, 230, 30);

        background.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background4.png"));
        jPanel2.add(background);
        background.setBounds(0, 0, 1000, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1016, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recipe_howtoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_recipe_howtoPropertyChange

    }//GEN-LAST:event_recipe_howtoPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookmarkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookmarkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookmarkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookmarkView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookmarkView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JScrollPane cooktimepane;
    private javax.swing.JScrollPane descriptionpane;
    private javax.swing.JScrollPane howtopane;
    private javax.swing.JScrollPane ingredientspane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextArea recipe_cooktime;
    public javax.swing.JTextArea recipe_description;
    public javax.swing.JTextArea recipe_howto;
    public javax.swing.JLabel recipe_image;
    public javax.swing.JTextArea recipe_ingredients;
    public javax.swing.JLabel recipe_name;
    // End of variables declaration//GEN-END:variables
}
