/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author azval
 */
public class CreateRecipe extends javax.swing.JFrame {

    /**
     * Creates new form CreateRecipe
     */
    public CreateRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        RecipeIDTextBox = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ExitButton = new javax.swing.JButton();
        SubmitButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        HowToCookTextBox = new javax.swing.JTextField();
        CookTimesTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        IngredientsTextBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DescriptionTextBox = new javax.swing.JTextField();
        background6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create Recipe");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(266, 24, 260, 60);

        RecipeIDTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecipeIDTextBoxActionPerformed(evt);
            }
        });
        jPanel1.add(RecipeIDTextBox);
        RecipeIDTextBox.setBounds(130, 170, 170, 22);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Recipe I.D:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 170, 80, 20);

        ExitButton.setBackground(new java.awt.Color(255, 51, 51));
        ExitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ExitButton.setText("Return");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ExitButton);
        ExitButton.setBounds(390, 460, 90, 30);

        SubmitButton.setBackground(new java.awt.Color(153, 255, 153));
        SubmitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(SubmitButton);
        SubmitButton.setBounds(260, 460, 90, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Ingredients:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(38, 278, 79, 25);

        HowToCookTextBox.setMinimumSize(new java.awt.Dimension(60, 20));
        jPanel1.add(HowToCookTextBox);
        HowToCookTextBox.setBounds(130, 380, 642, 47);

        CookTimesTextBox.setMinimumSize(new java.awt.Dimension(60, 20));
        jPanel1.add(CookTimesTextBox);
        CookTimesTextBox.setBounds(130, 330, 642, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("How to cook:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(38, 393, 100, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cook Times:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(38, 336, 90, 25);

        IngredientsTextBox.setMinimumSize(new java.awt.Dimension(60, 20));
        IngredientsTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientsTextBoxActionPerformed(evt);
            }
        });
        jPanel1.add(IngredientsTextBox);
        IngredientsTextBox.setBounds(130, 270, 642, 40);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Description:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(38, 220, 80, 20);

        DescriptionTextBox.setMinimumSize(new java.awt.Dimension(60, 20));
        DescriptionTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DescriptionTextBoxActionPerformed(evt);
            }
        });
        jPanel1.add(DescriptionTextBox);
        DescriptionTextBox.setBounds(130, 210, 644, 40);

        background6.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background6.png"));
        jPanel1.add(background6);
        background6.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IngredientsTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientsTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientsTextBoxActionPerformed

    private void RecipeIDTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecipeIDTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecipeIDTextBoxActionPerformed

    private void DescriptionTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescriptionTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DescriptionTextBoxActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // saves created recipe to recipe database
        
        
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminControlPanel admin = new AdminControlPanel();
        admin.setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CookTimesTextBox;
    private javax.swing.JTextField DescriptionTextBox;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField HowToCookTextBox;
    private javax.swing.JTextField IngredientsTextBox;
    private javax.swing.JTextField RecipeIDTextBox;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
