/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author masta
 */
public class CreateAccount extends javax.swing.JFrame {

	/**
	 * Creates new form CreateAccount
	 */
	public CreateAccount() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CreateAccountReEnterPassword = new javax.swing.JPasswordField();
        CreateAccountPassword = new javax.swing.JPasswordField();
        createaccount_label = new javax.swing.JLabel();
        reenter_label = new javax.swing.JLabel();
        CreateAccountUsername = new javax.swing.JTextField();
        CreateAccountReturnButton = new javax.swing.JButton();
        password_label = new javax.swing.JLabel();
        username_label = new javax.swing.JLabel();
        CreateAccountCreateButton = new javax.swing.JButton();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        CreateAccountReEnterPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(CreateAccountReEnterPassword);
        CreateAccountReEnterPassword.setBounds(428, 241, 150, 21);

        CreateAccountPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jPanel1.add(CreateAccountPassword);
        CreateAccountPassword.setBounds(428, 205, 150, 23);

        createaccount_label.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        createaccount_label.setForeground(new java.awt.Color(255, 153, 153));
        createaccount_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createaccount_label.setText("CREATE ACCOUNT");
        jPanel1.add(createaccount_label);
        createaccount_label.setBounds(291, 100, 231, 34);

        reenter_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reenter_label.setText("Re-enter Password:");
        jPanel1.add(reenter_label);
        reenter_label.setBounds(264, 239, 141, 17);

        CreateAccountUsername.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CreateAccountUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(CreateAccountUsername);
        CreateAccountUsername.setBounds(428, 172, 150, 21);

        CreateAccountReturnButton.setBackground(new java.awt.Color(153, 153, 153));
        CreateAccountReturnButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateAccountReturnButton.setText("Return");
        CreateAccountReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountReturnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateAccountReturnButton);
        CreateAccountReturnButton.setBounds(213, 305, 178, 51);

        password_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        password_label.setText("Password:");
        jPanel1.add(password_label);
        password_label.setBounds(264, 206, 100, 22);

        username_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        username_label.setText("Username:");
        jPanel1.add(username_label);
        username_label.setBounds(264, 170, 100, 17);

        CreateAccountCreateButton.setBackground(new java.awt.Color(153, 153, 153));
        CreateAccountCreateButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CreateAccountCreateButton.setText("Create Account");
        CreateAccountCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountCreateButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CreateAccountCreateButton);
        CreateAccountCreateButton.setBounds(410, 306, 178, 51);

        background2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background2.png"));
        jPanel1.add(background2);
        background2.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateAccountReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_CreateAccountReturnButtonActionPerformed

    private void CreateAccountCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountCreateButtonActionPerformed
        // creates a new account and store it in account database
        String user = CreateAccountUsername.getText();
        String pass = CreateAccountPassword.getText();
        String repass = CreateAccountReEnterPassword.getText();
        //assigns the username, password, and reentered password to their own variables
        
        //database connection details
        String host = "jdbc:mysql://csi2999.mysql.database.azure.com:3306/login";
        int port = 3306;
        String DatabaseUsername = "csi2999";
        String DatabasePassword = "bhl7^W0O#qq2";
        String Database = "login";
        
        //verify if passwords match with this if structure 
        if(!pass.equals(repass)) {
            JOptionPane.showMessageDialog(null,"Passwords do not match.");
            return;
        }
        try{
            /*try {
                //establish connection with the database
                Class.forName("mssql-jdbc-12.2.0.jre8");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(CreateAccount.class.getName()).log(Level.SEVERE, null, ex);
            }*/
            Connection conn = DriverManager.getConnection(host, DatabaseUsername, DatabasePassword);
         
            //check if username exists
            String checkQuery = "SELECT username FROM user WHERE username = ?";
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            checkStmt.setString(1, user);

            ResultSet resultSet = checkStmt.executeQuery();
            
            // If the username already exists, notify the user
            if (resultSet.next()) {
                JOptionPane.showMessageDialog(null,"Username already exists!");            
            }
            else{
                // Insert the new account into the database
                String insertQuery = "INSERT INTO user (username, password) VALUES (?, ?)";
                PreparedStatement insertStmt = conn.prepareStatement(insertQuery);
                insertStmt.setString(1, user);
                insertStmt.setString(2, pass);
                insertStmt.executeUpdate();
                JOptionPane.showMessageDialog(null,"Account created successfully!");
                
                //close resources
                resultSet.close();
                checkStmt.close();
                conn.close();
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_CreateAccountCreateButtonActionPerformed

    private void CreateAccountUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CreateAccountUsernameActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreateAccount().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccountCreateButton;
    private javax.swing.JPasswordField CreateAccountPassword;
    private javax.swing.JPasswordField CreateAccountReEnterPassword;
    private javax.swing.JButton CreateAccountReturnButton;
    private javax.swing.JTextField CreateAccountUsername;
    private javax.swing.JLabel background2;
    private javax.swing.JLabel createaccount_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel password_label;
    private javax.swing.JLabel reenter_label;
    private javax.swing.JLabel username_label;
    // End of variables declaration//GEN-END:variables
}
