/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ethan
 */
public class DeleteRecipe extends javax.swing.JFrame {
    
    /**
     * Creates new form DeleteRecipe
     */
    public DeleteRecipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        r = new javax.swing.JTextField();
        CheckRecipeButton = new javax.swing.JButton();
        labelTextEnter1 = new javax.swing.JLabel();
        DeleteComboBox = new javax.swing.JComboBox<>();
        labelTextEnter = new javax.swing.JLabel();
        DeleteRecipeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Cook = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        Desc = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        How = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Ingr = new javax.swing.JTextArea();
        DeleteRecipeReturnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        background7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);
        jPanel2.add(r);
        r.setBounds(200, 90, 160, 30);

        CheckRecipeButton.setBackground(new java.awt.Color(255, 204, 204));
        CheckRecipeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CheckRecipeButton.setText("Check Recipe");
        CheckRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckRecipeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(CheckRecipeButton);
        CheckRecipeButton.setBounds(500, 440, 130, 27);

        labelTextEnter1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTextEnter1.setForeground(new java.awt.Color(153, 255, 153));
        labelTextEnter1.setText("Enter Recipe Name:");
        jPanel2.add(labelTextEnter1);
        labelTextEnter1.setBounds(10, 90, 190, 36);

        DeleteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select a Catagory", "Breakfast", "Lunch", "Dinner" }));
        jPanel2.add(DeleteComboBox);
        DeleteComboBox.setBounds(550, 100, 200, 22);

        labelTextEnter.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        labelTextEnter.setForeground(new java.awt.Color(153, 255, 153));
        labelTextEnter.setText("Select Catagory:");
        jPanel2.add(labelTextEnter);
        labelTextEnter.setBounds(390, 90, 150, 36);

        DeleteRecipeButton.setBackground(new java.awt.Color(255, 102, 102));
        DeleteRecipeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteRecipeButton.setText("Delete");
        DeleteRecipeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecipeButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteRecipeButton);
        DeleteRecipeButton.setBounds(670, 440, 100, 30);

        Cook.setEditable(false);
        Cook.setColumns(20);
        Cook.setLineWrap(true);
        Cook.setRows(5);
        Cook.setWrapStyleWord(true);
        jScrollPane3.setViewportView(Cook);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(20, 280, 369, 150);

        Desc.setEditable(false);
        Desc.setColumns(20);
        Desc.setLineWrap(true);
        Desc.setRows(5);
        Desc.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Desc);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(20, 130, 369, 132);

        How.setEditable(false);
        How.setColumns(20);
        How.setLineWrap(true);
        How.setRows(5);
        How.setWrapStyleWord(true);
        jScrollPane1.setViewportView(How);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(400, 130, 370, 132);

        Ingr.setEditable(false);
        Ingr.setColumns(20);
        Ingr.setLineWrap(true);
        Ingr.setRows(5);
        Ingr.setWrapStyleWord(true);
        jScrollPane4.setViewportView(Ingr);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(400, 280, 370, 150);

        DeleteRecipeReturnButton.setBackground(new java.awt.Color(255, 102, 204));
        DeleteRecipeReturnButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteRecipeReturnButton.setText("Return");
        DeleteRecipeReturnButton.setName("DeleteRecipeReturnButton"); // NOI18N
        DeleteRecipeReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecipeReturnButtonActionPerformed(evt);
            }
        });
        jPanel2.add(DeleteRecipeReturnButton);
        DeleteRecipeReturnButton.setBounds(87, 18, 102, 34);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 255, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Recipe");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(268, 6, 258, 60);

        background7.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\\\images\\background.png"));
        jPanel2.add(background7);
        background7.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(804, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteRecipeReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecipeReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AdminControlPanel admin = new AdminControlPanel();
        admin.setVisible(true);
    }//GEN-LAST:event_DeleteRecipeReturnButtonActionPerformed

    private void CheckRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckRecipeButtonActionPerformed
        // displays selected recipe in text areas 
        
         //database connection details
        String host = "jdbc:mysql://csi2999.mysql.database.azure.com:3306/login";
        int port = 3306;
        String DatabaseUsername = "csi2999";
        String DatabasePassword = "bhl7^W0O#qq2";
        String Database = "login";
        String tableName = "";
        
        try{
            //create connection
            Connection conn = DriverManager.getConnection(host, DatabaseUsername, DatabasePassword);
            Statement stm = conn.createStatement();
            String item = (String)DeleteComboBox.getSelectedItem();
            String cat = r.getText();
            switch (item) {
                case "Breakfast":
                    tableName = "recipes.breakfast";
                    break;
                case "Lunch":
                    tableName = "recipes.lunch";
                    break;
                case "Dinner":
                    tableName = "recipes.dinner";
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "Invalid recipe catagory.");
                    return; // Exit the method if the recipe name is invalid
            }
                  
            
            ResultSet rs = stm.executeQuery("SELECT * FROM " + tableName +" WHERE recipe_name = '"+cat+"'");
            if (rs.next()){
                Desc.setText(rs.getString("description"));
                How.setText(rs.getString("how_to_cook"));
                Cook.setText(rs.getString("cook_time"));
                Ingr.setText(rs.getString("ingredients"));
                conn.close();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_CheckRecipeButtonActionPerformed

    private void DeleteRecipeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecipeButtonActionPerformed
        // removes the recipe from the database
        //database connection details
        String host = "jdbc:mysql://csi2999.mysql.database.azure.com:3306/login";
        int port = 3306;
        String DatabaseUsername = "csi2999";
        String DatabasePassword = "bhl7^W0O#qq2";
        String Database = "login";
        
        
        try {
            String RecipeCatagory = (String)DeleteComboBox.getSelectedItem();
            String RecipeNameInput = r.getText();
            String tableName = "";
            Connection conn = DriverManager.getConnection(host, DatabaseUsername, DatabasePassword);
            
            switch (RecipeCatagory) {
                case "Breakfast":
                    tableName = "recipes.breakfast";
                    break;
                case "Lunch":
                    tableName = "recipes.lunch";
                    break;
                case "Dinner":
                    tableName = "recipes.dinner";
                    break;
                default:
                    JOptionPane.showMessageDialog(rootPane, "Invalid recipe catagory.");
                    return; // Exit the method if the recipe name is invalid
            }

            try (PreparedStatement stmt = conn.prepareStatement("DELETE FROM " + tableName + " WHERE Recipe_name = ?")) {
                stmt.setString(1, RecipeNameInput);

                int rowsDeleted = stmt.executeUpdate();

                if (rowsDeleted > 0) {
                    JOptionPane.showMessageDialog(rootPane, RecipeNameInput + " deleted successfully!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Recipe not found.");
                }
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(rootPane, "Error occurred while deleting the recipe.");
            }
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(rootPane, "Error connecting to the database.");
        }
        
        
    }//GEN-LAST:event_DeleteRecipeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteRecipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteRecipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CheckRecipeButton;
    private javax.swing.JTextArea Cook;
    private javax.swing.JComboBox<String> DeleteComboBox;
    private javax.swing.JButton DeleteRecipeButton;
    private javax.swing.JButton DeleteRecipeReturnButton;
    private javax.swing.JTextArea Desc;
    private javax.swing.JTextArea How;
    private javax.swing.JTextArea Ingr;
    private javax.swing.JLabel background7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelTextEnter;
    private javax.swing.JLabel labelTextEnter1;
    private javax.swing.JTextField r;
    // End of variables declaration//GEN-END:variables
}
