/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author harsi
 */
public class Dinner extends javax.swing.JFrame {

    /**
     * Creates new form Dinner
     */
    public Dinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dinnerCookTimes = new javax.swing.JTextField();
        dinnerIngredients = new javax.swing.JTextField();
        dinnerHowTo = new javax.swing.JTextField();
        dinnerDescription = new javax.swing.JTextField();
        dinnerReturnButton = new javax.swing.JButton();
        dinnerDropDown = new javax.swing.JComboBox<>();
        dinner = new javax.swing.JLabel();
        dinnerimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        dinnerCookTimes.setForeground(new java.awt.Color(255, 255, 255));
        dinnerCookTimes.setBorder(null);
        jPanel1.add(dinnerCookTimes);
        dinnerCookTimes.setBounds(26, 291, 376, 153);
        jPanel1.add(dinnerIngredients);
        dinnerIngredients.setBounds(420, 291, 365, 153);
        jPanel1.add(dinnerHowTo);
        dinnerHowTo.setBounds(420, 120, 365, 153);

        dinnerDescription.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dinnerDescriptionComponentHidden(evt);
            }
        });
        jPanel1.add(dinnerDescription);
        dinnerDescription.setBounds(26, 120, 376, 153);

        dinnerReturnButton.setText("Return");
        dinnerReturnButton.setName("dinnerReturnButton"); // NOI18N
        dinnerReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinnerReturnButtonActionPerformed(evt);
            }
        });
        jPanel1.add(dinnerReturnButton);
        dinnerReturnButton.setBounds(461, 79, 92, 23);

        dinnerDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(dinnerDropDown);
        dinnerDropDown.setBounds(174, 79, 228, 22);

        dinner.setBackground(new java.awt.Color(153, 255, 153));
        dinner.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        dinner.setForeground(new java.awt.Color(102, 255, 153));
        dinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dinner.setText("Dinner Recipes");
        jPanel1.add(dinner);
        dinner.setBounds(260, 0, 270, 60);

        dinnerimage.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\Dinner Image.png"));
        jPanel1.add(dinnerimage);
        dinnerimage.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dinnerDescriptionComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dinnerDescriptionComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dinnerDescriptionComponentHidden

    private void dinnerReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinnerReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AllRecipes a = new AllRecipes();
        a.setVisible(true);
    }//GEN-LAST:event_dinnerReturnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dinner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dinner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dinner;
    private javax.swing.JTextField dinnerCookTimes;
    private javax.swing.JTextField dinnerDescription;
    private javax.swing.JComboBox<String> dinnerDropDown;
    private javax.swing.JTextField dinnerHowTo;
    private javax.swing.JTextField dinnerIngredients;
    private javax.swing.JButton dinnerReturnButton;
    private javax.swing.JLabel dinnerimage;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
