/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Guis;

/**
 *
 * @author shabe
 */
public class Dinner extends javax.swing.JPanel {

    /**
     * Creates new form Dinner
     */
    public Dinner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dinner = new javax.swing.JLabel();
        dinnerDropDown = new javax.swing.JComboBox<>();
        dinnerReturnButton = new javax.swing.JButton();
        dinnerHowTo = new javax.swing.JTextField();
        dinnerDescription = new javax.swing.JTextField();
        dinnerCookTimes = new javax.swing.JTextField();
        dinnerIngredients = new javax.swing.JTextField();
        dinnerimage = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        setLayout(null);

        dinner.setBackground(new java.awt.Color(0, 0, 0));
        dinner.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        dinner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dinner.setText("Dinner Recipes");
        add(dinner);
        dinner.setBounds(260, 0, 280, 70);

        dinnerDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(dinnerDropDown);
        dinnerDropDown.setBounds(174, 79, 228, 22);

        dinnerReturnButton.setText("Return");
        dinnerReturnButton.setName("dinnerReturnButton"); // NOI18N
        dinnerReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dinnerReturnButtonActionPerformed(evt);
            }
        });
        add(dinnerReturnButton);
        dinnerReturnButton.setBounds(461, 79, 92, 23);
        add(dinnerHowTo);
        dinnerHowTo.setBounds(420, 120, 365, 153);

        dinnerDescription.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dinnerDescriptionComponentHidden(evt);
            }
        });
        add(dinnerDescription);
        dinnerDescription.setBounds(26, 120, 376, 153);

        dinnerCookTimes.setForeground(new java.awt.Color(255, 255, 255));
        dinnerCookTimes.setBorder(null);
        add(dinnerCookTimes);
        dinnerCookTimes.setBounds(26, 291, 376, 153);
        add(dinnerIngredients);
        dinnerIngredients.setBounds(420, 291, 365, 153);

        dinnerimage.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\Dinner Image.png"));
        dinnerimage.setPreferredSize(new java.awt.Dimension(800, 500));
        add(dinnerimage);
        dinnerimage.setBounds(0, 0, 800, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void dinnerReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dinnerReturnButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dinnerReturnButtonActionPerformed

    private void dinnerDescriptionComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dinnerDescriptionComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dinnerDescriptionComponentHidden


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dinner;
    private javax.swing.JTextField dinnerCookTimes;
    private javax.swing.JTextField dinnerDescription;
    private javax.swing.JComboBox<String> dinnerDropDown;
    private javax.swing.JTextField dinnerHowTo;
    private javax.swing.JTextField dinnerIngredients;
    private javax.swing.JButton dinnerReturnButton;
    private javax.swing.JLabel dinnerimage;
    // End of variables declaration//GEN-END:variables
}
