/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author azval
 */
public class Lunch extends javax.swing.JFrame {

    /**
     * Creates new form Lunch
     */
    public Lunch() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LunchListDropDown = new javax.swing.JComboBox<>();
        LunchReturnButton = new javax.swing.JButton();
        DescriptionTxt = new javax.swing.JTextField();
        HowToCookTxt = new javax.swing.JTextField();
        IngredientsTxt = new javax.swing.JTextField();
        CookTimesTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 51, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Lunch");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 34, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LunchListDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(LunchListDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, -1, -1));

        LunchReturnButton.setText("Return");
        jPanel2.add(LunchReturnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        DescriptionTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        DescriptionTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(DescriptionTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 387, 151));

        HowToCookTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        HowToCookTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        HowToCookTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HowToCookTxtActionPerformed(evt);
            }
        });
        jPanel2.add(HowToCookTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 383, 151));

        IngredientsTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        IngredientsTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IngredientsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngredientsTxtActionPerformed(evt);
            }
        });
        jPanel2.add(IngredientsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 230, 383, 156));

        CookTimesTxt.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        CookTimesTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(CookTimesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 387, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HowToCookTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HowToCookTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HowToCookTxtActionPerformed

    private void IngredientsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngredientsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IngredientsTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lunch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CookTimesTxt;
    private javax.swing.JTextField DescriptionTxt;
    private javax.swing.JTextField HowToCookTxt;
    private javax.swing.JTextField IngredientsTxt;
    private javax.swing.JComboBox<String> LunchListDropDown;
    private javax.swing.JButton LunchReturnButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
