/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author azval
 */
public class Lunch extends javax.swing.JFrame {

    /**
     * Creates new form Lunch
     */
    public Lunch() {
        initComponents();
        UpdateCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        LunchHowToCook = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        LunchCookTimes = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        LunchDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        LunchIngredients = new javax.swing.JTextArea();
        LunchDropDown = new javax.swing.JComboBox<>();
        lunchReturnButton = new javax.swing.JButton();
        lunch = new javax.swing.JLabel();
        lunchimage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 102, 102));
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(102, 255, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);

        jScrollPane3.setViewportView(null);

        LunchHowToCook.setEditable(false);
        LunchHowToCook.setColumns(20);
        LunchHowToCook.setLineWrap(true);
        LunchHowToCook.setRows(5);
        LunchHowToCook.setWrapStyleWord(true);
        jScrollPane3.setViewportView(LunchHowToCook);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(410, 120, 380, 160);

        LunchCookTimes.setEditable(false);
        LunchCookTimes.setColumns(20);
        LunchCookTimes.setLineWrap(true);
        LunchCookTimes.setRows(5);
        LunchCookTimes.setWrapStyleWord(true);
        jScrollPane4.setViewportView(LunchCookTimes);

        jPanel2.add(jScrollPane4);
        jScrollPane4.setBounds(10, 300, 380, 160);

        LunchDescription.setEditable(false);
        LunchDescription.setColumns(20);
        LunchDescription.setLineWrap(true);
        LunchDescription.setRows(5);
        LunchDescription.setWrapStyleWord(true);
        jScrollPane5.setViewportView(LunchDescription);

        jPanel2.add(jScrollPane5);
        jScrollPane5.setBounds(10, 120, 380, 160);

        LunchIngredients.setEditable(false);
        LunchIngredients.setColumns(20);
        LunchIngredients.setLineWrap(true);
        LunchIngredients.setRows(5);
        LunchIngredients.setWrapStyleWord(true);
        jScrollPane2.setViewportView(LunchIngredients);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(410, 300, 380, 160);

        LunchDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LunchDropDownActionPerformed(evt);
            }
        });
        jPanel2.add(LunchDropDown);
        LunchDropDown.setBounds(174, 79, 228, 22);

        lunchReturnButton.setText("Return");
        lunchReturnButton.setName("lunchReturnButton"); // NOI18N
        lunchReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lunchReturnButtonActionPerformed(evt);
            }
        });
        jPanel2.add(lunchReturnButton);
        lunchReturnButton.setBounds(461, 79, 92, 23);

        lunch.setBackground(new java.awt.Color(0, 0, 0));
        lunch.setFont(new java.awt.Font("Helvetica Neue", 0, 36)); // NOI18N
        lunch.setForeground(new java.awt.Color(255, 255, 204));
        lunch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lunch.setText("Lunch Recipes");
        jPanel2.add(lunch);
        lunch.setBounds(250, 0, 280, 70);

        lunchimage.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background4.png"));
        jPanel2.add(lunchimage);
        lunchimage.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lunchReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lunchReturnButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        AllRecipes a = new AllRecipes();
        a.setVisible(true);
    }//GEN-LAST:event_lunchReturnButtonActionPerformed

    private void LunchDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LunchDropDownActionPerformed
        //combo box function
        //database connection details
        String host = "jdbc:mysql://csi2999.mysql.database.azure.com:3306/login";
        int port = 3306;
        String DatabaseUsername = "csi2999";
        String DatabasePassword = "bhl7^W0O#qq2";
        String Database = "login";
        
        
             //try block to execute the sql query to get matching info from combobox
        try{
            //create connection
            Connection conn = DriverManager.getConnection(host, DatabaseUsername, DatabasePassword);
            Statement stm = conn.createStatement();
            Object item = LunchDropDown.getSelectedItem();
                        ResultSet rs = stm.executeQuery("SELECT * FROM recipes.lunch WHERE recipe_name = '"+item+"'");
                        rs.next();
                        LunchDescription.setText(rs.getString("description"));
                        LunchHowToCook.setText(rs.getString("how_to_cook"));
                        LunchCookTimes.setText(rs.getString("cook_time"));
                        LunchIngredients.setText(rs.getString("ingredients"));
                        conn.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_LunchDropDownActionPerformed
    private void UpdateCombo(){
        //gather all information from lunch table
        String sql = "select * from recipes.lunch";
        
        //database connection details
        String host = "jdbc:mysql://csi2999.mysql.database.azure.com:3306/login";
        int port = 3306;
        String DatabaseUsername = "csi2999";
        String DatabasePassword = "bhl7^W0O#qq2";
        String Database = "login";
        
      
        
        //try block to execute the sql query to get all info from lunch table
        try{
            //create connection
            Connection conn = DriverManager.getConnection(host, DatabaseUsername, DatabasePassword);
            
            // execute query
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            
            //add names to combo box
            while(rs.next()){
                LunchDropDown.addItem(rs.getString("recipe_name"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lunch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Lunch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea LunchCookTimes;
    private javax.swing.JTextArea LunchDescription;
    private javax.swing.JComboBox<String> LunchDropDown;
    private javax.swing.JTextArea LunchHowToCook;
    private javax.swing.JTextArea LunchIngredients;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lunch;
    private javax.swing.JButton lunchReturnButton;
    private javax.swing.JLabel lunchimage;
    // End of variables declaration//GEN-END:variables
}
