/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Guis;

/**
 *
 * @author masta
 */
public class UserMain extends javax.swing.JFrame {
       
	/**
	 * Creates new form UserMain
	 */
        public UserMain(){
            initComponents();
        }
	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainmenu_label = new javax.swing.JLabel();
        allrecipes_label = new javax.swing.JButton();
        singout_button = new javax.swing.JButton();
        bookmarks_label = new javax.swing.JButton();
        background3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setFocusCycleRoot(false);
        setFocusable(false);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));
        addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                formPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        mainmenu_label.setBackground(new java.awt.Color(255, 255, 0));
        mainmenu_label.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        mainmenu_label.setForeground(new java.awt.Color(153, 255, 153));
        mainmenu_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mainmenu_label.setText("Main Menu");
        jPanel1.add(mainmenu_label);
        mainmenu_label.setBounds(331, 96, 142, 38);

        allrecipes_label.setBackground(new java.awt.Color(255, 255, 102));
        allrecipes_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        allrecipes_label.setText("All Recipes");
        allrecipes_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allrecipes_labelActionPerformed(evt);
            }
        });
        jPanel1.add(allrecipes_label);
        allrecipes_label.setBounds(185, 171, 174, 76);

        singout_button.setBackground(new java.awt.Color(153, 153, 153));
        singout_button.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        singout_button.setText("Sign Out");
        singout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singout_buttonActionPerformed(evt);
            }
        });
        jPanel1.add(singout_button);
        singout_button.setBounds(355, 286, 89, 38);

        bookmarks_label.setBackground(new java.awt.Color(255, 255, 102));
        bookmarks_label.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        bookmarks_label.setText("Bookmarks");
        bookmarks_label.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookmarks_labelActionPerformed(evt);
            }
        });
        jPanel1.add(bookmarks_label);
        bookmarks_label.setBounds(440, 171, 174, 76);

        background3.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir") +"\\src\\main\\java\\Guis\\images\\background3.png"));
        background3.setOpaque(true);
        jPanel1.add(background3);
        background3.setBounds(0, 0, 800, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(816, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void bookmarks_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookmarks_labelActionPerformed
        // TODO add your handling code here:
        dispose();
        BookmarkedRecipes bookmark = new BookmarkedRecipes();
        bookmark.setVisible(true);
        
    }//GEN-LAST:event_bookmarks_labelActionPerformed

    private void allrecipes_labelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allrecipes_labelActionPerformed
        // TODO add your handling code here:
        dispose();
        AllRecipes all = new AllRecipes();
        all.setVisible(true);
    }//GEN-LAST:event_allrecipes_labelActionPerformed

    private void singout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singout_buttonActionPerformed
        // TODO add your handling code here:
        dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_singout_buttonActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new UserMain().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allrecipes_label;
    private javax.swing.JLabel background3;
    private javax.swing.JButton bookmarks_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mainmenu_label;
    private javax.swing.JButton singout_button;
    // End of variables declaration//GEN-END:variables
}
